<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Digital_Clock</RootNamespace>
    <AssemblyName>Digital Clock</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CircularProgressBar" Version="2.8.0.16" NoWarn="NU1701" />
    <PackageReference Include="WinFormAnimation" Version="1.6.0.4" NoWarn="NU1701" />
  </ItemGroup>
</Project>
